Repository deislabs/spiderlightning, pull requests merged in 2022-08, with the labels that each got.

#148 refactor configs
  crates/kv/src/implementors/azblob.rs
  crates/lockd/src/implementors/etcd.rs
  crates/mq/src/implementors/azsbus.rs
  crates/pubsub-confluent-kafka/src/lib.rs
  crates/runtime-configs/src/implementors/envvars.rs
  crates/runtime-configs/src/implementors/mod.rs
  crates/runtime-configs/src/implementors/usersecrets.rs
  crates/runtime-configs/src/lib.rs
  crates/runtime-configs/src/providers/envvars.rs
  crates/runtime-configs/src/providers/mod.rs
  crates/runtime-configs/src/providers/usersecrets.rs
  examples/configs-demo/usersecrets_slightfile.toml
  examples/multi_capability-demo-clang/bindings/kv.c
  examples/multi_capability-demo-clang/bindings/mq.c
  slight/src/commands/run.rs
Labels: 💫 refactor

#147 dynamic dispatch of pubsub
  Cargo.lock
  Cargo.toml
  crates/kv/src/implementors/azblob.rs
  crates/kv/src/lib.rs
  crates/lockd/src/implementors/etcd.rs
  crates/lockd/src/lib.rs
  crates/mq/src/lib.rs
  crates/pubsub-confluent-kafka/src/lib.rs
  crates/pubsub/Cargo.toml
  crates/pubsub/src/implementors/apache_kafka.rs
  crates/pubsub/src/implementors/mod.rs
  crates/pubsub/src/lib.rs
  crates/pubsub/src/providers/confluent.rs
  crates/pubsub/src/providers/mod.rs
  examples/configs-demo/usersecrets_slightfile.toml
  examples/pubsub-consumer-demo/slightfile.toml
  examples/pubsub-consumer-demo/src/main.rs
  examples/pubsub-producer-demo/slightfile.toml
  examples/pubsub-producer-demo/src/main.rs
  slight/Cargo.toml
  slight/src/commands/run.rs
Labels: 💫 refactor

#135 feat(kv): added aws dynamodb to kv capability
  Cargo.lock
  Makefile
  crates/kv/Cargo.toml
  crates/kv/src/implementors/awsdynamodb.rs
  crates/kv/src/implementors/mod.rs
  crates/kv/src/lib.rs
  examples/kv-demo/kvawsdynamodb_slightfile.toml
  slight/src/commands/run.rs
  tests/integration.rs
  tests/kv-test/kvawsdynamodb_slightfile.toml
  tests/kv-test/src/main.rs
Labels: ✨ feature

#151 feat: added prefix slight to all crates
  Cargo.lock
  crates/events-api/Cargo.toml
  crates/events/Cargo.toml
  crates/events/src/lib.rs
  crates/kv/Cargo.toml
  crates/kv/src/implementors/azblob.rs
  crates/kv/src/implementors/filesystem.rs
  crates/kv/src/lib.rs
  crates/lockd/Cargo.toml
  crates/lockd/src/implementors/etcd.rs
  crates/lockd/src/lib.rs
  crates/mq/Cargo.toml
  crates/mq/src/implementors/azsbus.rs
  crates/mq/src/lib.rs
  crates/pubsub/Cargo.toml
  crates/pubsub/src/implementors/apache_kafka.rs
  crates/pubsub/src/lib.rs
  crates/runtime-configs/Cargo.toml
  crates/runtime-configs/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/resource.rs
  slight/Cargo.toml
  slight/src/commands/run.rs
Labels: ✨ feature

#158 modified az pipeline to include az app config secrets
  build/azure-pipeline/workflow-pr.yml
Labels: ✨ feature

#162 adding cache to az pipeline
  build/azure-pipeline/workflow-pr.yml
Labels: 💫 refactor

#143 feat: added HTTP capability
  .gitignore
  Cargo.lock
  Cargo.toml
  Makefile
  build/azure-pipeline/workflow-pr.yml
  crates/events/src/lib.rs
  crates/http-api/Cargo.toml
  crates/http-api/src/lib.rs
  crates/http-handler-macro/Cargo.toml
  crates/http-handler-macro/src/lib.rs
  crates/http/Cargo.toml
  crates/http/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
  crates/runtime/src/resource.rs
  examples/configs-demo/usersecrets_slightfile.toml
  examples/http-demo/Cargo.lock
  examples/http-demo/Cargo.toml
  examples/http-demo/slightfile.toml
  examples/http-demo/src/main.rs
  slight/Cargo.toml
  slight/src/commands/run.rs
  slight/src/main.rs
  wit/http-handler.wit
  wit/http-types.wit
  wit/http.wit
Labels: ✨ feature

#153 implements az-app-config
  .github/workflows/ci.yaml
  Cargo.lock
  Makefile
  build.rs
  build/azure-pipeline/workflow-pr.yml
  crates/kv/Cargo.toml
  crates/lockd/Cargo.toml
  crates/mq/Cargo.toml
  crates/pubsub/Cargo.toml
  crates/runtime-configs/Cargo.toml
  crates/runtime-configs/src/implementors/azapp.rs
  crates/runtime-configs/src/implementors/mod.rs
  crates/runtime-configs/src/lib.rs
  examples/configs-demo/azapp_slightfile.toml
  examples/configs-demo/usersecrets_slightfile.toml
  slight/src/commands/run.rs
  tests/configs-test/Cargo.lock
  tests/configs-test/Cargo.toml
  tests/configs-test/azapp_slightfile.toml
  tests/configs-test/envvars_slightfile.toml
  tests/configs-test/src/main.rs
  tests/configs-test/usersecrets_slightfile.toml
  tests/integration.rs
Labels: ✨ feature

#171 temporarily removing windows from our matrix of pipelines
  build/azure-pipeline/workflow-pr.yml
Labels: 🐛 bug

#172 making dependency versions less specific
  crates/events-api/Cargo.toml
  crates/events/Cargo.toml
  crates/http-api/Cargo.toml
  crates/http-handler-macro/Cargo.toml
  crates/http/Cargo.toml
  crates/kv/Cargo.toml
  crates/lockd/Cargo.toml
  crates/mq/Cargo.toml
  crates/pubsub/Cargo.toml
  crates/runtime-configs/Cargo.toml
  crates/runtime/Cargo.toml
  examples/kv-demo/Cargo.toml
  slight/Cargo.toml
Labels: 💫 refactor

#169 refactor: removed unused config in Builder
  crates/runtime/src/lib.rs
Labels: 💫 refactor

#176 moved aws dynamo db from future resource examples to implemented resource examples in primer doc
  docs/primer.md
Labels: 📚 docs

#173 organized pubsub toml like the others capability tomls
  crates/pubsub/Cargo.toml
Labels: 💫 refactor

#175 feat: new store and instance per http/events handler
  Cargo.lock
  Cargo.toml
  crates/common/Cargo.toml
  crates/common/src/lib.rs
  crates/events-api/Cargo.toml
  crates/events-api/src/lib.rs
  crates/events/Cargo.toml
  crates/events/gen_main.rs
  crates/events/src/lib.rs
  crates/http/Cargo.toml
  crates/http/src/lib.rs
  crates/kv/Cargo.toml
  crates/kv/src/implementors/azblob.rs
  crates/kv/src/lib.rs
  crates/lockd/Cargo.toml
  crates/lockd/src/implementors/etcd.rs
  crates/lockd/src/lib.rs
  crates/mq/Cargo.toml
  crates/mq/src/implementors/azsbus.rs
  crates/mq/src/lib.rs
  crates/pubsub/Cargo.toml
  crates/pubsub/src/implementors/apache_kafka.rs
  crates/pubsub/src/lib.rs
  crates/runtime-configs/Cargo.toml
  crates/runtime-configs/src/lib.rs
  crates/runtime/Cargo.toml
  crates/runtime/src/ctx.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/resource.rs
  slight/Cargo.toml
  slight/src/commands/run.rs
Labels: ✨ feature

#178 added name explanation onto README
  README.md
  docs/images/readme2.jpg
Labels: 📚 docs

#177 contributing a full-fledged app for future demos
  Makefile
  examples/app-demos/README.md
  examples/app-demos/restaurant-backend/Cargo.lock
  examples/app-demos/restaurant-backend/Cargo.toml
  examples/app-demos/restaurant-backend/slightfile.toml
  examples/app-demos/restaurant-backend/src/main.rs
Labels: ✨ feature

#186 renaming legacy var names
  crates/common/src/lib.rs
  crates/kv/src/implementors/azblob.rs
  crates/lockd/src/implementors/etcd.rs
  crates/mq/src/implementors/azsbus.rs
  crates/pubsub/src/implementors/apache_kafka.rs
  crates/runtime-configs/src/lib.rs
  examples/configs-demo/usersecrets_slightfile.toml
Labels: 💫 refactor
