Repository deislabs/spiderlightning, pull requests merged in 2022-10, with the labels that each got.

#213 added `new` command
  Cargo.lock
  Makefile
  slight/Cargo.toml
  slight/src/cli.rs
  slight/src/commands/add.rs
  slight/src/commands/mod.rs
  slight/src/commands/new.rs
  slight/src/lib.rs
  slight/src/main.rs
  templates/c/Makefile
  templates/c/slightfile.toml
  templates/c/src/main.c
  templates/rust/Cargo.toml
  templates/rust/slightfile.toml
  templates/rust/src/main.rs
Labels: ✨ feature

#214 created release.yml + installation scripts for easy install (inspired by rust and homebrew) + updated readme w/ install instructions
  .github/workflows/release.yml
  Makefile
  README.md
  install.ps1
  install.sh
Labels: 📚 docs, ✨ feature, 💫 refactor

#203 slightfile-design doc
  docs/slightfile-design.md
Labels: 📚 docs, 📐 proposal

#216 updating README getting started exp + other small doc changes
  README.md
  docs/slightfile-design.md
Labels: 📚 docs

#219 added support for macos-latest aarch64
  .devcontainer/setup.sh
  .github/workflows/ci.yaml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  Makefile
  build/azure-pipeline/workflow-pr.yml
  crates/pubsub/Cargo.toml
  install.ps1
  install.sh
Labels: ✨ feature, 💫 refactor

#223 fixed install script on MacOS
  install.sh
Labels: 🐛 bug, 📚 docs

#226 pre-kubecon patches
  Cargo.lock
  crates/http/Cargo.toml
  crates/http/src/lib.rs
  crates/mq/src/lib.rs
  examples/multi_capability-demo-clang/bindings/kv.c
  examples/multi_capability-demo-clang/bindings/kv.h
  slight/Cargo.toml
Labels: 🐛 bug, ✨ feature

#196 feat(test): added integration tests for kv redis implementaiton
  .github/workflows/ci.yaml
  Makefile
  build/azure-pipeline/workflow-pr.yml
  crates/kv/src/implementors/redis.rs
  tests/integration.rs
  tests/kv-test/kvredis_slightfile.toml
Labels: ✨ feature
