Repository deislabs/spiderlightning, pull requests merged in 2022-09, with the labels that each got.

#188 added service implementation 101 doc
  README.md
  docs/service-implementation-101.md
Labels: 📚 docs

#190 removing unused dependencies
  Cargo.lock
  crates/common/Cargo.toml
  crates/events/Cargo.toml
  crates/http-handler-macro/Cargo.toml
  crates/http/Cargo.toml
  crates/runtime-configs/Cargo.toml
  tests/http-test/Cargo.lock
Labels: 💫 refactor

#183 adding an implementor for pubsub that can be ran locally (i.e., Mosquitto)
  Cargo.lock
  Makefile
  crates/pubsub/Cargo.toml
  crates/pubsub/src/implementors/mod.rs
  crates/pubsub/src/implementors/mosquitto.rs
  crates/pubsub/src/lib.rs
  examples/configs-demo/usersecrets_slightfile.toml
  examples/pubsub-consumer-demo/caf_slightfile.toml
  examples/pubsub-consumer-demo/mosquitto_slightfile.toml
  examples/pubsub-consumer-demo/src/main.rs
  examples/pubsub-producer-demo/caf_slightfile.toml
  examples/pubsub-producer-demo/mosquitto_slightfile.toml
  slight/src/commands/run.rs
Labels: ✨ feature

#192 pubsub refactor
  Cargo.lock
  Makefile
  crates/pubsub/Cargo.toml
  crates/pubsub/src/implementors/apache_kafka.rs
  crates/pubsub/src/implementors/mosquitto.rs
  crates/pubsub/src/lib.rs
  crates/pubsub/src/providers/confluent.rs
  examples/http-demo/Cargo.lock
  examples/pubsub-consumer-demo/src/main.rs
  examples/pubsub-producer-demo/src/main.rs
  wit/pubsub.wit
  wit/types.wit
Labels: 💫 refactor

#194 feat: Redis key-value capability implementation
  Cargo.lock
  crates/kv/Cargo.toml
  crates/kv/src/implementors/mod.rs
  crates/kv/src/implementors/redis.rs
  crates/kv/src/lib.rs
  examples/kv-demo/kvredis_slightfile.toml
  slight/src/commands/run.rs
Labels: ✨ feature

#200 start of an sdk/slight_lib
  .github/workflows/ci.yaml
  Cargo.lock
  Makefile
  slight/Cargo.toml
  slight/src/commands/run.rs
  slight/src/commands/secret.rs
  slight/src/lib.rs
  slight/src/main.rs
  src/lib.rs
  src/sdk/mod.rs
  tests/configs-test/usersecrets_slightfile.toml
Labels: ✨ feature

#204 fixing typos in the service implementation 101 doc
  docs/service-implementation-101.md
Labels: 📚 docs

#205 adding more resources on the contributing section of the README
  README.md
Labels: 📚 docs

#207 fixing clippy issue on main
  crates/http-api/src/lib.rs
  crates/http/src/lib.rs
Labels: 🐛 bug
