Repository deislabs/spiderlightning, pull requests merged in 2023-04, with the labels that each got.

#283 test: added a messaging integration test
  Cargo.lock
  Makefile
  tests/Cargo.toml
  tests/build.rs
  tests/messaging-test/.cargo/config.toml
  tests/messaging-test/Cargo.lock
  tests/messaging-test/Cargo.toml
  tests/messaging-test/consumer.toml
  tests/messaging-test/messaging.slightfile.toml
  tests/messaging-test/src/bin/consumer_a.rs
  tests/messaging-test/src/bin/consumer_b.rs
  tests/messaging-test/src/lib.rs
  tests/src/lib.rs
Labels: 🧪 tests

#376 feat(slightfile): implement wildcard namespace for resources
  Cargo.lock
  crates/blob-store/src/lib.rs
  crates/common/src/state.rs
  crates/core/src/secret.rs
  crates/distributed-locking/src/lib.rs
  crates/keyvalue/src/lib.rs
  crates/messaging/src/lib.rs
  crates/runtime-configs/src/implementors/usersecrets.rs
  crates/runtime-configs/src/lib.rs
  crates/slightfile/Cargo.toml
  crates/slightfile/src/capability_store.rs
  crates/slightfile/src/lib.rs
  crates/slightfile/src/resource.rs
  crates/slightfile/src/secret_store.rs
  crates/slightfile/src/slightfile.rs
  crates/slightfile/tests/bad/dup-1.toml
  crates/slightfile/tests/bad/dup-2.toml
  crates/slightfile/tests/bad/dup-3.toml
  crates/slightfile/tests/good/dup-good-1.toml
  crates/slightfile/tests/good/dup-good-2.toml
  crates/slightfile/tests/good/dup-good-3.toml
  crates/slightfile/tests/good/msg.toml
  crates/sql/src/lib.rs
  src/commands/run.rs
  src/commands/secret.rs
  tests/build.rs
  tests/configs-test/us_slightfile.toml
  tests/src/lib.rs
  tests/wildcard-test/Cargo.lock
  tests/wildcard-test/Cargo.toml
  tests/wildcard-test/slightfile.toml
  tests/wildcard-test/src/lib.rs
Labels: ✨ feature

#387 new logo for SpiderLightning
  README.md
  docs/images/spiderlightning_logo_alt2.png
Labels: 📚 docs

#386 added cli option to link all caps needed for dynamic langs
  src/cli.rs
  src/commands/run.rs
  src/main.rs
Labels: ✨ feature

#389 fixed typo in slightfile of nats messaging example
  examples/messaging-consumer-demo/nats_slightfile.toml
  examples/messaging-producer-demo/nats_slightfile.toml
Labels: 🐛 bug

#388 fix(messaging): fixed a bug in `subscribe` function and moved filesystem implementation in house
  Cargo.lock
  crates/messaging/Cargo.toml
  crates/messaging/src/implementors/filesystem.rs
  crates/messaging/src/providers/fs.rs
  crates/messaging/src/providers/mod.rs
Labels: 🐛 bug

#390 http client requests can now have a body
  crates/http-client/src/lib.rs
  tests/http-test/src/lib.rs
Labels: ✨ feature
