Repository deislabs/spiderlightning, pull requests merged in 2023-02, with the labels that each got.

#322 tied slight version to interface version when using slight add or slight new
  slight/src/commands/add.rs
  slight/src/commands/new.rs
Labels: 🐛 bug

#327 reusing ci.yaml for releases
  .github/workflows/release.yml
Labels: 🚧 maintainer issue

#328 added workflow_call to on
  .github/workflows/ci.yaml
Labels: 🚧 maintainer issue

#329 add needs to release pipeline
  .github/workflows/release.yml
Labels: 🚧 maintainer issue

#330 added artifact communication between ci.yaml and release.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yml
Labels: 🚧 maintainer issue

#331 update path of downloaded artifacts in release pipeline
  .github/workflows/release.yml
Labels: 🚧 maintainer issue

#332 release.yml now downloads specific artifacts for release
  .github/workflows/release.yml
Labels: 🚧 maintainer issue

#325 Refactor: Re-structure slight repo
  Cargo.lock
  Cargo.toml
  Makefile
  crates/common/Cargo.toml
  crates/common/src/lib.rs
  crates/core/Cargo.toml
  crates/core/src/lib.rs
  crates/core/src/secret.rs
  crates/core/src/slightfile.rs
  crates/distributed-locking/Cargo.toml
  crates/distributed-locking/src/lib.rs
  crates/http-api/Cargo.toml
  crates/http-client/Cargo.toml
  crates/http-server/Cargo.toml
  crates/keyvalue/Cargo.toml
  crates/messaging/Cargo.toml
  crates/runtime-configs/Cargo.toml
  crates/runtime-configs/src/implementors/usersecrets.rs
  crates/runtime-configs/src/lib.rs
  crates/runtime/Cargo.toml
  crates/sql/src/lib.rs
  slight/Cargo.toml
  slight/src/commands/add.rs
  slight/src/commands/new.rs
  slight/src/commands/run.rs
  slight/src/commands/secret.rs
  src/lib.rs
  tests/Cargo.toml
  tests/build.rs
  tests/configs-test/us_slightfile.toml
  tests/src/lib.rs
Labels: 💫 refactor
