Repository deislabs/spiderlightning, pull requests merged in 2023-01, with the labels that each got.

#282 feat: renamed router http error to http-router-error
  crates/http-handler-macro/src/lib.rs
  crates/http/src/lib.rs
  examples/http-demo/src/main.rs
  tests/http-test/src/main.rs
  wit/http-handler.wit
  wit/http-types.wit
  wit/http.wit
Labels: ✨ feature

#284 feat: use conditional compilation for each service's implementation in messaging and keyvalue capabilities
  Cargo.toml
  build.rs
  crates/distributed-locking/Cargo.toml
  crates/distributed-locking/src/implementors/etcd.rs
  crates/distributed-locking/src/implementors/mod.rs
  crates/distributed-locking/src/lib.rs
  crates/distributed-locking/src/providers/mod.rs
  crates/http-api/Cargo.toml
  crates/http-handler-macro/src/lib.rs
  crates/http/Cargo.toml
  crates/keyvalue/Cargo.toml
  crates/keyvalue/src/implementors/awsdynamodb.rs
  crates/keyvalue/src/implementors/azblob.rs
  crates/keyvalue/src/implementors/filesystem.rs
  crates/keyvalue/src/implementors/mod.rs
  crates/keyvalue/src/implementors/redis.rs
  crates/keyvalue/src/lib.rs
  crates/keyvalue/src/providers/mod.rs
  crates/messaging/Cargo.toml
  crates/messaging/src/implementors/apache_kafka.rs
  crates/messaging/src/implementors/azsbus.rs
  crates/messaging/src/implementors/filesystem.rs
  crates/messaging/src/implementors/mod.rs
  crates/messaging/src/implementors/mosquitto.rs
  crates/messaging/src/lib.rs
  crates/messaging/src/providers/azure.rs
  crates/messaging/src/providers/confluent.rs
  crates/messaging/src/providers/mod.rs
  crates/runtime-configs/Cargo.toml
  crates/runtime-configs/src/lib.rs
  crates/runtime/Cargo.toml
  slight/Cargo.toml
  slight/src/commands/add.rs
  slight/src/commands/new.rs
  slight/src/commands/run.rs
  tests/configs-test/us_slightfile.toml
  tests/integration.rs
Labels: ✨ feature

#285 feat: added http-client capability and a reqwest implementation
  Cargo.lock
  Cargo.toml
  Makefile
  crates/common/src/lib.rs
  crates/distributed-locking/src/lib.rs
  crates/http-client/Cargo.toml
  crates/http-client/src/lib.rs
  crates/http-server/Cargo.toml
  crates/http-server/src/lib.rs
  crates/http/gen_main.rs
  crates/keyvalue/src/lib.rs
  crates/messaging/src/lib.rs
  crates/runtime-configs/src/lib.rs
  docs/primer.md
  examples/app-demos/restaurant-backend/src/main.rs
  examples/http-client-demo/Cargo.lock
  examples/http-client-demo/Cargo.toml
  examples/http-client-demo/slightfile.toml
  examples/http-client-demo/src/main.rs
  examples/http-server-demo/Cargo.lock
  examples/http-server-demo/Cargo.toml
  examples/http-server-demo/slightfile.toml
  examples/http-server-demo/src/main.rs
  slight/Cargo.toml
  slight/src/commands/add.rs
  slight/src/commands/run.rs
  tests/http-test/src/main.rs
  wit/http-client.wit
  wit/http-handler.wit
  wit/http-server.wit
  wit/http-types.wit
Labels: ⭐ epic

#304 small fix on http-client-demo
  examples/http-client-demo/src/main.rs
  examples/http-server-demo/Cargo.lock
Labels: 🐛 bug

#306 fix ci
  Makefile
Labels: 🐛 bug

#293 tests: added a http-client integration test
  tests/http-test/slightfile.toml
  tests/http-test/src/main.rs
  tests/integration.rs
Labels: 🧪 tests
