Repository deislabs/spiderlightning, pull requests merged in 2023-03, with the labels that each got.

#343 `slight` now pre-opens the `.` dir to allow filesystem access
  .gitignore
  crates/runtime/src/lib.rs
  tests/build.rs
  tests/filesystem-access-test/Cargo.lock
  tests/filesystem-access-test/Cargo.toml
  tests/filesystem-access-test/slightfile.toml
  tests/filesystem-access-test/src/main.rs
  tests/src/lib.rs
Labels: ✨ feature

#354 added NATS - a new implementor for the messaging capability!
  Cargo.lock
  Cargo.toml
  Makefile
  build/azure-pipeline/workflow-pr.yml
  crates/messaging/Cargo.toml
  crates/messaging/src/implementors/mod.rs
  crates/messaging/src/implementors/natsio.rs
  crates/messaging/src/lib.rs
  crates/runtime-configs/src/lib.rs
  examples/configs-demo/Cargo.lock
  examples/distributed-locking-demo/Cargo.lock
  examples/http-client-demo/Cargo.lock
  examples/http-server-demo/Cargo.lock
  examples/keyvalue-demo/Cargo.lock
  examples/messaging-consumer-demo/Cargo.lock
  examples/messaging-consumer-demo/nats_slightfile.toml
  examples/messaging-producer-demo/Cargo.lock
  examples/messaging-producer-demo/nats_slightfile.toml
  examples/multi_capability-demo/Cargo.lock
  examples/sql-demo/Cargo.lock
  src/commands/run.rs
Labels: ✨ feature

#342 enable handle_run to accept io redirect paths
  Cargo.lock
  Cargo.toml
  crates/runtime/Cargo.toml
  crates/runtime/src/lib.rs
  src/commands/run.rs
  src/commands/test/io-test.wasm
  src/commands/test/slightfile.toml
  src/main.rs
  tests/Cargo.toml
  tests/build.rs
  tests/io-test/Cargo.lock
  tests/io-test/Cargo.toml
  tests/io-test/slightfile.toml
  tests/io-test/src/main.rs
Labels: ✨ feature

#359 feat(http-server): Add WASI reactor support to http-server cap
  Cargo.lock
  Cargo.toml
  crates/common/src/context.rs
  crates/http-api/src/lib.rs
  crates/http-handler-macro/src/lib.rs
  crates/http-server-macro/Cargo.toml
  crates/http-server-macro/src/lib.rs
  crates/http-server/src/lib.rs
  crates/runtime/src/lib.rs
  crates/runtime/src/resource.rs
  examples/http-server-demo/Cargo.lock
  examples/http-server-demo/Cargo.toml
  examples/http-server-demo/src/lib.rs
  src/commands/run.rs
  tests/build.rs
  tests/configs-test/us_slightfile.toml
  tests/http-test/Cargo.lock
  tests/http-test/Cargo.toml
  tests/http-test/src/lib.rs
  tests/src/lib.rs
  wit/http-server-export.wit
  wit/http-server.wit
  wit/http-types.wit
Labels: ✨ feature

#357 made supported capabilities msg more maintaible
  src/commands/run.rs
Labels: 💫 refactor

#367 fix: add http-server-export to downloads
  src/commands/add.rs
  tests/src/lib.rs
Labels: 🐛 bug

#360 tests: Re-enable AWS integration tests
  Cargo.lock
  crates/keyvalue/Cargo.toml
  crates/keyvalue/src/implementors/awsdynamodb.rs
  crates/runtime-configs/src/lib.rs
  tests/keyvalue-test/keyvalue_awsdynamodb_slightfile.toml
  tests/keyvalue-test/keyvalue_azblob_slightfile.toml
  tests/keyvalue-test/keyvalue_filesystem_slightfile.toml
  tests/keyvalue-test/src/main.rs
  tests/src/lib.rs
Labels: 🧪 tests

#372 feat(blob-store): Add Azure Blob Storage implementation to wasi-blob-store capability
  Cargo.lock
  crates/blob-store/Cargo.toml
  crates/blob-store/src/container.rs
  crates/blob-store/src/implementors/azblob.rs
  crates/blob-store/src/implementors/mod.rs
  crates/blob-store/src/lib.rs
  examples/blob-store-demo/az_blob.toml
  src/commands/run.rs
  tests/blob-store-test/az_blob.toml
  tests/blob-store-test/src/main.rs
  tests/src/lib.rs
Labels: ✨ feature

#361 feat(blob-store): Add wasi-blob-store capability
  Cargo.lock
  Cargo.toml
  crates/blob-store/Cargo.toml
  crates/blob-store/src/container.rs
  crates/blob-store/src/implementors/aws_s3.rs
  crates/blob-store/src/implementors/azblob.rs
  crates/blob-store/src/implementors/mod.rs
  crates/blob-store/src/lib.rs
  crates/blob-store/src/read_stream.rs
  crates/blob-store/src/write_stream.rs
  crates/runtime/src/lib.rs
  examples/blob-store-demo/Cargo.lock
  examples/blob-store-demo/Cargo.toml
  examples/blob-store-demo/az_blob.toml
  examples/blob-store-demo/blob_s3.toml
  examples/blob-store-demo/src/main.rs
  src/commands/add.rs
  src/commands/run.rs
  tests/blob-store-test/Cargo.lock
  tests/blob-store-test/Cargo.toml
  tests/blob-store-test/az_blob.toml
  tests/blob-store-test/blob_s3.toml
  tests/blob-store-test/src/main.rs
  tests/blob-store-test/testfile0.txt
  tests/blob-store-test/testfile1.txt
  tests/blob-store-test/testfile2.txt
  tests/build.rs
  tests/src/lib.rs
  wit/blob-store.wit
  wit/blob-types.wit
Labels: ⭐ epic
